<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Review;
use Carbon\Carbon;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reviews = [
            [
                'author_name' => 'Marie Dupont',
                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}

                'author_location' => 'Paris (75)',
                'rating' => 5,
                'review_text' => 'Excellente entreprise ! Travaux de plomberie réalisés dans les délais avec un grand professionnalisme. Équipe très compétente et à l\'écoute. Je recommande vivement.',
                'review_date' => Carbon::now()->subDays(5),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'author_name' => 'Jean-Pierre Martin',
                'author_location' => 'Lyon (69)',
                'rating' => 5,
                'review_text' => 'Très satisfait de la rénovation de ma façade. Devis clair, prix compétitif et résultat impeccable. L\'équipe est ponctuelle et soignée.',
                'review_date' => Carbon::now()->subDays(12),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'author_name' => 'Sophie Durand',
                'author_location' => 'Marseille (13)',
                'rating' => 5,
                'review_text' => 'Isolation des combles réalisée rapidement et efficacement. Très bon rapport qualité/prix. Je recommande cette entreprise pour leur sérieux et leur expertise.',
                'review_date' => Carbon::now()->subDays(18),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'author_name' => 'Pierre Lefebvre',
                'author_location' => 'Toulouse (31)',
                'rating' => 5,
                'review_text' => 'Entreprise sérieuse et professionnelle. Travaux de plomberie et isolation réalisés avec soin. L\'équipe est très compétente et donne de bons conseils.',
                'review_date' => Carbon::now()->subDays(25),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'author_name' => 'Isabelle Moreau',
                'author_location' => 'Bordeaux (33)',
                'rating' => 5,
                'review_text' => 'Ravalement de façade impeccable ! Chantier propre, équipe professionnelle et respectueuse. Le résultat dépasse mes attentes. Merci !',
                'review_date' => Carbon::now()->subDays(30),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'author_name' => 'Thomas Bernard',
                'author_location' => 'Nantes (44)',
                'rating' => 5,
                'review_text' => 'Très bon suivi du projet du début à la fin. Travaux de rénovation énergétique bien réalisés. Je recommande sans hésitation.',
                'review_date' => Carbon::now()->subDays(40),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'author_name' => 'Christine Laurent',
                'author_location' => 'Strasbourg (67)',
                'rating' => 5,
                'review_text' => 'Entreprise à l\'écoute et réactive. Travaux de plomberie réalisés dans les règles de l\'art. Prix honnête et qualité au rendez-vous.',
                'review_date' => Carbon::now()->subDays(45),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'author_name' => 'Michel Robert',
                'author_location' => 'Lille (59)',
                'rating' => 5,
                'review_text' => 'Excellents travaux d\'isolation. L\'équipe est professionnelle, ponctuelle et très soigneuse. Je n\'hésiterai pas à les recontacter pour de futurs projets.',
                'review_date' => Carbon::now()->subDays(55),
                'is_verified' => true,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($reviews as $review) {
            Review::create($review);
        }
    }
}
